# Generated by Django 5.2.17 on 2026-09-11 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy_core', '0005_questions_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='answer_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='question_files/')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_files', to='academy_core.answer')),
            ],
        ),
        migrations.CreateModel(
            name='Question_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='question_files/')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_files', to='academy_core.questions')),
            ],
        ),
    ]
