# Generated by Django 5.2.17 on 2026-09-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0002_rename_message_message_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.IntegerField(choices=[(0, 'User'), (1, 'assistant')]),
        ),
    ]
