# Generated by Django 6.0.6 on 2026-07-03 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_transaction_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='session',
        ),
    ]
