# Generated by Django 5.2.8 on 2026-08-26 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_remove_transaction_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.IntegerField(choices=[(1, 'Stripe'), (2, 'Paypal'), (3, 'Cash')]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'delivery'), (2, 'Completed')], default=0),
        ),
    ]
